### ISSUE TITLE
Ids of original data split

### ISSUE THREAD

**Issue by Demfier** [gombru/multi-modal-hate-speech#1]
Hi @gombru 

Thank you for the dataset. Would you be able to make the `splits` folder available as well? It's not included in the current zip. I am actually running some experiments on your dataset and it would be useful if I have the split you used for reporting results in your paper for comparison and consistency purposes.

Thanks,
Gaurav.

**Comment by gombru** [comment]
Hi! 
I forgot to include the splits file in the zip. I attach them here, and will upload the dataset file as soon as possible.

[splits.zip](https://github.com/gombru/multi-modal-hate-speech/files/3813993/splits.zip)
